name: godotclassreference
description: Class reference for Godot Engine.

publish_to: none
doc_time: 2020-08-12
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.3+38

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_launcher_icons: ^0.9.2

  scrollable_positioned_list: ^0.2.2

  flutter_svg: ^0.23.0+1

  url_launcher: ^6.0.12

  # store values to local
  shared_preferences: ^2.0.8

  # read package info from code
  package_info: ^2.0.2

  # xml parser
  xml: ^5.3.1

  flutter:
    sdk: flutter

  flutter_highlight:
    git:
      url: https://github.com/GodotDocMobile/highlight.dart.git/
      path: flutter_highlight
      ref: generate-gdscript

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  gettext: ^1.2.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon.png"
  android: true
  ios: true
  image_path_android: "icon_transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
      # pngs
    - drawer_header.png
      # svgs
    - svgs/2.1/
    - svgs/3.0/
    - svgs/3.1/
    - svgs/3.2/
    - svgs/3.3/
    - svgs/3.4/
    - svgs/icon.svg
      # xmls
    - xmls/2.0/
    - xmls/2.1/
    - xmls/3.0/
    - xmls/3.1/
    - xmls/3.2/
    - xmls/3.3/
    - xmls/3.4/
      # file index
    - xmls/

#    - translations/2.1/
#    - translations/3.0/
#    - translations/3.1/
#    - translations/3.2/
#    - translations/3.3/

    - godot_license/