name: godotclassreference
description: Third party godot class reference reader.

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.6+61

environment:
  sdk: '>=3.0.0'

dependencies:
  bbob_dart: ^0.2.1
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gettext: ^2.0.1
  flutter_highlight:
    git:
      url: https://github.com/GodotDocMobile/highlight.dart.git/
      path: flutter_highlight
      ref: generate-gdscript
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  package_info_plus: ^8.0.3
  scrollable_positioned_list: ^0.3.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.12
  window_manager: ^0.4.2
  xml: ^6.3.0

dev_dependencies: 
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # pngs
    - drawer_header.png
    # svgs
    - svgs/2.1/
    - svgs/3.0/
    - svgs/3.1/
    - svgs/3.2/
    - svgs/3.3/
    - svgs/3.4/
    - svgs/3.5/
    - svgs/3.6/
    - svgs/4.0/
    - svgs/4.1/
    - svgs/4.2/
    - svgs/4.3/
    - svgs/icon.svg
    # xmls
    - xmls/2.0/
    - xmls/2.1/
    - xmls/3.0/
    - xmls/3.1/
    - xmls/3.2/
    - xmls/3.3/
    - xmls/3.4/
    - xmls/3.5/
    - xmls/3.6/
    - xmls/4.0/
    - xmls/4.1/
    - xmls/4.2/
    - xmls/4.3/
    # file index
    - xmls/
    - translations/3.4/
    - translations/3.5/
    - translations/3.6/
    - translations/4.0/
    - translations/4.1/
    - translations/4.2/
    - translations/4.3/

    - godot_license/

  fonts:
    - family: JetbrainsMono
      fonts:
        - asset: font/JetBrainsMono-VariableFont_wght.ttf
